### ISSUE TITLE
tar_git fails to checkout repo with submodules that have . in their name

### ISSUE THREAD

**Issue by rinigus** [MeeGoIntegration/boss-launcher-webhook#44]
I have an issue with checking out one of my packaging repositories: pkg-mapnik. It looks like something starts infinite loop when running:

```
bash tar_git --url https://github.com/rinigus/pkg-mapnik --debian N --dumb N --outdir TEST
```

Its always reproducible  and prevents using this repo for OBS packaging.

**Comment by larstiq** [comment]
At first I thought this might be related to the recent local submodule changes, or the less recent relative submodule url changes, but no.

Already a commit as old as 9f6ea8102837bfcc5ea6b37af8bb9967c98065c1 has broken logic for handling the mapnik repository. To start the process check out https://github.com/mapnik/mapnik.git

That has 4 submodules:

    [submodule "test/data"]
            path = test/data
            url = https://github.com/mapnik/test-data.git
            branch = master
    [submodule "test/data-visual"]
            path = test/data-visual
            url = https://github.com/mapnik/test-data-visual.git
            branch = master
    [submodule "deps/mapbox/variant"]
            path = deps/mapbox/variant
            url = https://github.com/mapbox/variant.git
            branch = master
    [submodule "deps/mapbox/geometry"]
            path = deps/mapbox/geometry
            url = https://github.com/mapbox/geometry.hpp.git
            branch = master


If you try giving one of those to tar_git as the top level there will be no infinite looping, instead terminating on a lack of rpm dir.  Something curious happens with variant and geometry though:

    + git submodule --quiet update --init --force --
    + test -d
    + pushd
    + handle_submodules
    + '[' -f .gitmodules ']'
    + popd
    + git submodule update --recursive --init --force
    Submodule path '.mason': checked out '727bd41628d4104fbd5bb5753f642fbca4ce6919'
    + popd
    /home/larstiq/src/jolla/boss-launcher-webhook/src/service/tar_git: line 771: popd: directory stack empty

They have a mason submodule for which the url and path variables end up empty, causing us to pushd without an argument.

    [submodule ".mason"]
            path = .mason
            url = https://github.com/mapbox/mason.git

**Comment by larstiq** [comment]
One thing that's wrong for sure is `name=$(echo $submod | cut -d= -f1 | cut -d. -f2)` in the presence of submodules with a . in the name.  For the input `submodule..mason.url=https://github.com/mapbox/mason.git` that produces an empty name.

**Comment by larstiq** [comment]
After fixing the '.' being blindly used as a separator https://github.com/rinigus/pkg-mapnik  succesfully checks out.

**Comment by rinigus** [comment]
Excellent! Thank you very much for looking into it. Please let me know when I can use it in OBS
